trigger: none
pr: none

stages:
- stage: Destroy
  displayName: Destroy Terraform Resources
  jobs:
  - job: Destroy
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    # Install Terraform
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.3.10'

    # Terraform Init (same backend as deploy)
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: azurerm
        command: init
        backendServiceArm: Billing-Subscription(af504235-2f6d-4469-aa25-251f498730fc)
        backendAzureRmStorageAccountName: azdevopsvenkat
        backendAzureRmContainerName: terraform
        backendAzureRmKey: terraform.tfstate

    # Terraform Destroy
    - task: TerraformTask@5
      displayName: Terraform Destroy
      inputs:
        provider: azurerm
        command: destroy
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: Billing-Subscription(af504235-2f6d-4469-aa25-251f498730fc)
